FROM gcr.io/google_containers/heapster-grafana-amd64:v4.4.3

ADD grafana-azure-monitor-datasource /var/lib/grafana/plugins/grafana-azure-monitor-datasource

ADD raintank-kubernetes-app /var/lib/grafana/plugins/raintank-kubernetes-app 
